version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "1230:1230"
    volumes:
      - ./client:/21i_1230_frontend
    networks:
      - app-network

  auth:
    build:
      context: ./Auth
    ports:
      - "3230:3230"
    volumes:
      - ./Auth:/21i_1230_backend
    networks:
      - app-network
    depends_on:
      - mongodb

  classrooms:
    build:
      context: ./Classrooms
    ports:
      - "3231:3231"
    volumes:
      - ./Classrooms:/21i_1230_backend
    networks:
      - app-network
    depends_on:
      - mongodb

  event-bus:
    build:
      context: ./event-bus
    ports:
      - "3232:3232"
    volumes:
      - ./event-bus:/21i_1230_backend
    networks:
      - app-network
    depends_on:
      - mongodb

  post:
    build:
      context: ./Post
    ports:
      - "3233:3233"
    volumes:
      - ./Post:/21i_1230_backend
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
